# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Release

on:
  release:
    types: [ created ]
  push:
    branches: [ release ]
jobs:
  PyPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
      - uses: actions/upload-artifact@v2
        with:
          name: pypi
          path: dist/
  Mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup pyenv
        env: 
          PYTHON_CONFIGURE_OPTS: "--enable-framework"
        uses: "gabrielfalcao/pyenv-action@v5"
        with:
          default: 3.6.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install gooey pyinstaller
      - name: Clone g2p
        run: git clone https://github.com/roedoejet/g2p.git $GITHUB_WORKSPACE/g2p
      - name: Build
        run: pyenv local 3.6.9 && pyenv global 3.6.9 && cd $GITHUB_WORKSPACE/convertextract && pyinstaller convertextract.spec
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: convertextract/dist/
      - name: zip
        run: |
          echo "::set-env name=PKG_VERSION::$(python3 -c "import pkg_resources; print(pkg_resources.get_distribution('convertextract').version)")"
          zip -r release.zip convertextract/dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PKG_VERSION }}
          release_name: Release ${{ env.PKG_VERSION }}
          draft: false
          prerelease: true
      - name: Upload Release Assets
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: macOS.zip
          asset_content_type: application/zip