# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Release

on:
  release:
    types: [ created ]
  push:
    branches: [ release ]
jobs:
  PyPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
  Mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup pyenv
        env: 
          PYTHON_CONFIGURE_OPTS: "--enable-shared"
        uses: "gabrielfalcao/pyenv-action@v5"
        with:
          default: 3.6.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install gooey pyinstaller
      - name: Clone g2p
        run: git clone https://github.com/roedoejet/g2p.git $GITHUB_WORKSPACE/g2p
      - name: Build
        run: pyenv local 3.6.9 && pyenv global 3.6.9 && cd $GITHUB_WORKSPACE/convertextract && pyinstaller convertextract.spec
      - name: Zip
        run: zip $GITHUB_WORKSPACE/convertextract/dist/Convertextract.zip $GITHUB_WORKSPACE/convertextract/dist/Convertextract.app
      - uses: actions/upload-artifact@v2
        with:
          name: macOS-build
          path: $GITHUB_WORKSPACE/convertextract/dist/Convertextract.zip